
# Create the ecommerce database
DROP DATABASE IF EXISTS ecommerce;
CREATE DATABASE ecommerce;

# Use the ecommerce database
USE ecommerce;

# Creating the denormalized table and loading the data into it
CREATE TABLE ecomm_denom_table
(
ORDER_ID VARCHAR(100),
CUSTOMER_ID VARCHAR(100),
ORDER_STATUS VARCHAR(20),
ORDER_PURCHASE_TIMESTAMP DATETIME,
ORDER_APPROVED_AT DATETIME,
ORDER_DELIVERED_CARRIER_DATE DATETIME,
ORDER_DELIVERED_CUSTOMER_DATE DATETIME,
ORDER_ESTIMATED_DELIVERY_DATE DATETIME,
CUSTOMER_UNIQUE_ID VARCHAR(100),
CUSTOMER_ZIP_CODE_PREFIX VARCHAR(10),
CUSTOMER_CITY VARCHAR(100),
CUSTOMER_STATE CHAR(2),
GEOLOCATION_LAT DECIMAL(20,10),
GEOLOCATION_LNG DECIMAL(20,10),
PRODUCT_ID VARCHAR(100),
SELLER_ID VARCHAR(100),
PRICE DECIMAL(20,3),
FREIGHT_VALUE DECIMAL(20,3),
PRODUCT_CATEGORY_NAME VARCHAR(200),
PRODUCT_WEIGHT_G DECIMAL(20,3),
VOLUMETRIC_WEIGHT DECIMAL(20,3),
SHIPPING_LIMIT_DATE DATETIME,
ORDER_ITEM_ID VARCHAR(100),
SELLER_STATE CHAR(2),
PAYMENT_TYPE VARCHAR(200),
PAYMENT_INSTALLMENTS INT,
PAYMENT_SEQUENTIAL INT,
TOTAL_PAYMENT_VALUE DECIMAL(20,3),
SELLER_TO_CARRIER_DELIVERYTIME DECIMAL(20,3),
CARRIER_TO_CUSTOMER_DELIVERY_TIME DECIMAL(20,3),
SELLER_DISPATCH_TIME VARCHAR(10),
CUSTOMER_DELIVERY_TIME VARCHAR(10),
PRIMARY KEY (ORDER_ID, ORDER_ITEM_ID)
);

CREATE TABLE seller
(
SELLER_ID VARCHAR(100) PRIMARY KEY,
SELLER_STATE CHAR(2)
);

CREATE TABLE product
(
PRODUCT_ID VARCHAR(100) PRIMARY KEY,
PRODUCT_CATEGORY_NAME VARCHAR(200),
PRODUCT_WEIGHT_G DECIMAL(20,3),
VOLUMETRIC_WEIGHT DECIMAL(20,3)
);

CREATE TABLE customer
(
CUSTOMER_ID VARCHAR(100) PRIMARY KEY,
CUSTOMER_CITY VARCHAR(100),
CUSTOMER_STATE CHAR(2)
);

CREATE TABLE payment
(
ORDER_ID VARCHAR(100) PRIMARY KEY,
PAYMENT_TYPE VARCHAR(200),
PAYMENT_INSTALLMENTS INT,
PAYMENT_SEQUENTIAL INT,
TOTAL_PAYMENT_VALUE DECIMAL(20,3)
);

DROP TABLE IF EXISTS geolocation;
CREATE TABLE geolocation
(
CUSTOMER_ZIP_CODE_PREFIX VARCHAR(10),
GEOLOCATION_LAT DECIMAL(20,10),
GEOLOCATION_LNG DECIMAL(20,10),
PRIMARY KEY (GEOLOCATION_LAT, GEOLOCATION_LNG)
);

CREATE TABLE orders
(
ORDER_ID VARCHAR(100),
CUSTOMER_ID VARCHAR(100),
GEOLOCATION_LAT DECIMAL(20,10),
GEOLOCATION_LNG DECIMAL(20,10),
ORDER_STATUS VARCHAR(20),
ORDER_PURCHASE_TIMESTAMP DATETIME,
ORDER_APPROVED_AT DATETIME,
ORDER_DELIVERED_CARRIER_DATE DATETIME,
ORDER_DELIVERED_CUSTOMER_DATE DATETIME,
ORDER_ESTIMATED_DELIVERY_DATE DATETIME,
SELLER_TO_CARRIER_DELIVERYTIME DECIMAL(20,3),
CARRIER_TO_CUSTOMER_DELIVERY_TIME DECIMAL(20,3),
SELLER_DISPATCH_TIME VARCHAR(10),
CUSTOMER_DELIVERY_TIME VARCHAR(10),
PRIMARY KEY (ORDER_ID, CUSTOMER_ID)
);

CREATE TABLE order_item
(
ORDER_ID VARCHAR(100),
ORDER_ITEM_ID VARCHAR(100),
PRODUCT_ID VARCHAR(100),
SELLER_ID VARCHAR(100),
PRICE DECIMAL(20,3),
FREIGHT_VALUE DECIMAL(20,3),
PRIMARY KEY (ORDER_ID, ORDER_ITEM_ID)
);